<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/** It shows which field is/are missing. */
enum AccountPostPayment400ApplicationJSONPathIssuesField: string
{
    case ReferenceReferenceNo = 'reference.referenceNo';
    case PaymentMethodToken = 'paymentMethod.token';
    case PaymentMethodCreditCardTrack1 = 'paymentMethod.creditCard.track1';
    case PaymentMethodCreditCardTrack2 = 'paymentMethod.creditCard.track2';
    case PaymentMethodAch = 'paymentMethod.ach';
    case PaymentMethodPaypal = 'paymentMethod.paypal';
    case PaymentMethodDebitBillPay = 'paymentMethod.debitBillPay';
    case PaymentMethodApplePay = 'paymentMethod.applePay';
    case PaymentMethodGooglePay = 'paymentMethod.googlePay';
}
