<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class AccountGetPaymentsResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * Example response
     * 
     * @var ?array<mixed> $payments
     */
	
    public ?array $payments = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $accountGetPayments403ApplicationJSONObject
     */
	
    public ?array $accountGetPayments403ApplicationJSONObject = null;
    
    /**
     * **Not Found**\
     * 
     * \
     * When you'll get `401 Unauthorized` response:
     * - When there are no Accounts/Orders/Payment found.
     * 
     * 
     * @var ?array<string, mixed> $accountGetPayments404ApplicationJSONObject
     */
	
    public ?array $accountGetPayments404ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $accountGetPayments500ApplicationJSONObject
     */
	
    public ?array $accountGetPayments500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $accountGetPayments503ApplicationJSONObject
     */
	
    public ?array $accountGetPayments503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->payments = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->accountGetPayments403ApplicationJSONObject = null;
		$this->accountGetPayments404ApplicationJSONObject = null;
		$this->accountGetPayments500ApplicationJSONObject = null;
		$this->accountGetPayments503ApplicationJSONObject = null;
	}
}
