<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class AccountPostCustomerResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\AccountPostCustomer200ApplicationJSON $accountPostCustomer200ApplicationJSONObject
     */
	
    public ?AccountPostCustomer200ApplicationJSON $accountPostCustomer200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->accountPostCustomer200ApplicationJSONObject = null;
	}
}
