<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class CreateDocumentRequestResponse
{
    /**
     * **Bad Request**\
     * 
     * \
     * The request body contains a malformed request or is incomplete.
     * 
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\ZodError> $badRequestMinifiedZodError
     */
	
    public ?array $badRequestMinifiedZodError = null;
    
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?string $internalServerError
     */
	
    public ?string $internalServerError = null;
    
    /**
     * **Not Found**\
     * 
     * \
     * When you'll get `404 Not Found` response:
     * - The Organization doesn't exist.
     * - None of the Onboarding Applications matches the provided deletion status.
     * - The Onboarding Application doesn't exist.
     * - The Application belonging to the User or Application Token doesn't exist.
     * - The User of the email sender doesn't exist.
     * 
     * 
     * @var ?string $notFound
     */
	
    public ?string $notFound = null;
    
    /**
     * **Created**
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\OnboardingDocumentRequestCreate $onboardingDocumentRequestCreate
     */
	
    public ?\TheLogicStudio\ExactPayments\Models\Shared\OnboardingDocumentRequestCreate $onboardingDocumentRequestCreate = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?string $serviceUnavailable
     */
	
    public ?string $serviceUnavailable = null;
    
    /**
     * **Unauthorized**\
     * 
     * \
     * When you'll get `401 Unauthorized` response:
     * - The User or Application Token is invalid.
     * - The User or Application Token doesn't have permission to create Document Requests.
     * 
     * 
     * @var ?string $unauthorized
     */
	
    public ?string $unauthorized = null;
    
	public function __construct()
	{
		$this->badRequestMinifiedZodError = null;
		$this->contentType = "";
		$this->internalServerError = null;
		$this->notFound = null;
		$this->onboardingDocumentRequestCreate = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->serviceUnavailable = null;
		$this->unauthorized = null;
	}
}
