<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/**
 * CreateOnboardingResponseBody - **Not Found**\
 * 
 * \
 * When you'll get `404 Not Found` response:
 * - The default Workflow doesn't exist.
 * - The system token associated to the Workflow doesn't exist.
 * - The Organization doesn't exist.
 * 
 * 
 * @package TheLogicStudio\ExactPayments\Models\Operations
 * @access public
 */
class CreateOnboardingResponseBody
{
    /**
     * Error Message.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\Message $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Operations\Message>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Message $message = null;
    
    /**
     * Format Type.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\CreateOnboardingType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Operations\CreateOnboardingType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateOnboardingType $type = null;
    
	public function __construct()
	{
		$this->message = null;
		$this->type = null;
	}
}
