<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/** Indicates the type of Payment Method stored in Exact Payments Vault, `card` value will be returned for Card Payment Methods. */
enum GetCustomerCustomerIdPaymentMethodToken200ApplicationJSONCardSchemaType: string
{
    case Card = 'card';
}
