<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class GetOrdersRequest
{
    /**
     * The maximum number of items to retrieve within the current page of results.
     * 
     * @var ?int $dollarLimit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=$limit')]
    public ?int $dollarLimit = null;
    
    /**
     * The number of records to be skipped per call. By default, starts with `0` and you should provide the current value plus the `$limit` value in subsequent calls to retrieve following sets of values (pages). So it will skip the number of records on the previous page and bring the next set of records.
     * 
     * @var ?int $dollarSkip
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=$skip')]
    public ?int $dollarSkip = null;
    
    /**
     * Datetime to limit the search to, in ISO8601 format. Defaults to today
     * 
     * @var ?\DateTime $to
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=to,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $to = null;
    
    /**
     * Datetime to start the search from, in ISO8601 format. Defaults to one month ago. Maximum search window is 6 months.
     * 
     * @var ?\DateTime $from
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=from,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $from = null;
    
	public function __construct()
	{
		$this->dollarLimit = null;
		$this->dollarSkip = null;
		$this->to = null;
		$this->from = null;
	}
}
