<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class GetOrdersResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\GetOrders403ApplicationJSON $getOrders403ApplicationJSONObject
     */
	
    public ?GetOrders403ApplicationJSON $getOrders403ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\GetOrders500ApplicationJSON $getOrders500ApplicationJSONObject
     */
	
    public ?GetOrders500ApplicationJSON $getOrders500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\GetOrders503ApplicationJSON $getOrders503ApplicationJSONObject
     */
	
    public ?GetOrders503ApplicationJSON $getOrders503ApplicationJSONObject = null;
    
    /**
     * Details of an existing orders.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\OrderSearch $orderSearch
     */
	
    public ?\TheLogicStudio\ExactPayments\Models\Shared\OrderSearch $orderSearch = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOrders403ApplicationJSONObject = null;
		$this->getOrders500ApplicationJSONObject = null;
		$this->getOrders503ApplicationJSONObject = null;
		$this->orderSearch = null;
	}
}
