<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class GetOrdersResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $getOrders403ApplicationJSONObject
     */
	
    public ?array $getOrders403ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $getOrders500ApplicationJSONObject
     */
	
    public ?array $getOrders500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $getOrders503ApplicationJSONObject
     */
	
    public ?array $getOrders503ApplicationJSONObject = null;
    
    /**
     * Details of an existing orders.
     * 
     * @var ?array<string, mixed> $orderSearch
     */
	
    public ?array $orderSearch = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOrders403ApplicationJSONObject = null;
		$this->getOrders500ApplicationJSONObject = null;
		$this->getOrders503ApplicationJSONObject = null;
		$this->orderSearch = null;
	}
}
