<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class GetPaymentsResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * Example response
     * 
     * @var ?array<mixed> $payments
     */
	
    public ?array $payments = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $getPayments403ApplicationJSONObject
     */
	
    public ?array $getPayments403ApplicationJSONObject = null;
    
    /**
     * **Not Found**\
     * 
     * \
     * When you'll get `401 Unauthorized` response:
     * - When there are no Accounts/Orders/Payment found.
     * 
     * 
     * @var ?array<string, mixed> $getPayments404ApplicationJSONObject
     */
	
    public ?array $getPayments404ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $getPayments500ApplicationJSONObject
     */
	
    public ?array $getPayments500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $getPayments503ApplicationJSONObject
     */
	
    public ?array $getPayments503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->payments = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getPayments403ApplicationJSONObject = null;
		$this->getPayments404ApplicationJSONObject = null;
		$this->getPayments500ApplicationJSONObject = null;
		$this->getPayments503ApplicationJSONObject = null;
	}
}
