<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class GetReportRequest
{
    /**
     * The ID of the report query
     * 
     * @var string $reportId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=reportId')]
    public string $reportId;
    
    /**
     * The fields that will be returned in the report.
     * 
     * @var ?string $select
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=select')]
    public ?string $select = null;
    
    /**
     * The format of the file that will be downloaded.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\Format $format
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=format')]
    public ?Format $format = null;
    
	public function __construct()
	{
		$this->reportId = "";
		$this->select = null;
		$this->format = null;
	}
}
