<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class ListDocumentRequestByTokenRequest
{
    /**
     * The Onboarding Application Document Request Token. The Token can be found in the Upload Document link URL sent via the Document Request email using [Request Document](/operations/createDocumentRequest) API endpoint.
     * 
     * @var string $documentRequestToken
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=documentRequestToken')]
    public string $documentRequestToken;
    
	public function __construct()
	{
		$this->documentRequestToken = "";
	}
}
