<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PostPaymentResponse
{
    /**
     * Payment Created
     * 
     * @var mixed $twoHundredAndOneApplicationJsonPayment
     */
	
    public mixed $twoHundredAndOneApplicationJsonPayment = null;
    
    /**
     * **Bad Request**\
     * 
     * When there are errors in the payload
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostPaymentResponseBody $fourHundredApplicationJsonObject
     */
	
    public ?PostPaymentResponseBody $fourHundredApplicationJsonObject = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostPaymentPaymentsResponseBody $fourHundredAndThreeApplicationJsonObject
     */
	
    public ?PostPaymentPaymentsResponseBody $fourHundredAndThreeApplicationJsonObject = null;
    
    /**
     * **Unprocessable Content**
     * 
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostPaymentPaymentsResponseResponseBody $fourHundredAndTwentyTwoApplicationJsonObject
     */
	
    public ?PostPaymentPaymentsResponseResponseBody $fourHundredAndTwentyTwoApplicationJsonObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostPaymentPaymentsResponse500ResponseBody $fiveHundredApplicationJsonObject
     */
	
    public ?PostPaymentPaymentsResponse500ResponseBody $fiveHundredApplicationJsonObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostPaymentPaymentsResponse503ResponseBody $fiveHundredAndThreeApplicationJsonObject
     */
	
    public ?PostPaymentPaymentsResponse503ResponseBody $fiveHundredAndThreeApplicationJsonObject = null;
    
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;
    
	public function __construct()
	{
		$this->twoHundredAndOneApplicationJsonPayment = null;
		$this->fourHundredApplicationJsonObject = null;
		$this->fourHundredAndThreeApplicationJsonObject = null;
		$this->fourHundredAndTwentyTwoApplicationJsonObject = null;
		$this->fiveHundredApplicationJsonObject = null;
		$this->fiveHundredAndThreeApplicationJsonObject = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
