<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/**
 * PostAccountAccountIdOrdersOrderIdPayResponseBody - OK
 * 
 * @package TheLogicStudio\ExactPayments\Models\Operations
 * @access public
 */
class PostAccountAccountIdOrdersOrderIdPayResponseBody
{
    /**
     * Order details response object.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\Order $order
     */
	#[\JMS\Serializer\Annotation\SerializedName('order')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Operations\Order')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Order $order = null;
    
    /**
     * Payment identifier.
     * 
     * @var ?string $paymentId
     */
	#[\JMS\Serializer\Annotation\SerializedName('paymentId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $paymentId = null;
    
	public function __construct()
	{
		$this->order = null;
		$this->paymentId = null;
	}
}
