<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PostAccountAccountIdOrdersResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Order created.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\OrderResponse $orderResponse
     */
	
    public ?\TheLogicStudio\ExactPayments\Models\Shared\OrderResponse $orderResponse = null;
    
    /**
     * **Bad Request**\
     * 
     * When there are errors in the payload
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrders400ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrders400ApplicationJSONObject = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrders403ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrders403ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrders500ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrders500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrders503ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrders503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->orderResponse = null;
		$this->postAccountAccountIdOrders400ApplicationJSONObject = null;
		$this->postAccountAccountIdOrders403ApplicationJSONObject = null;
		$this->postAccountAccountIdOrders500ApplicationJSONObject = null;
		$this->postAccountAccountIdOrders503ApplicationJSONObject = null;
	}
}
