<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/**
 * PostAccountAccountIdOrders400ApplicationJSON - **Bad Request**\
 * 
 * When there are errors in the payload
 * 
 * 
 * @package TheLogicStudio\ExactPayments\Models\Operations
 * @access public
 */
class PostAccountAccountIdOrders400ApplicationJSON
{
    /**
     * Code of the validation error.
     * 
     * @var ?string $code
     */
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $code = null;
    
    /**
     * Message explaining the validation error.
     * 
     * @var ?string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $message = null;
    
    /**
     * $pathIssues
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Operations\PostAccountAccountIdOrders400ApplicationJSONPathIssues> $pathIssues
     */
	#[\JMS\Serializer\Annotation\SerializedName('pathIssues')]
    #[\JMS\Serializer\Annotation\Type('array<TheLogicStudio\ExactPayments\Models\Operations\PostAccountAccountIdOrders400ApplicationJSONPathIssues>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $pathIssues = null;
    
    /**
     * Request identifier in UUID format.
     * 
     * @var ?string $requestId
     */
	#[\JMS\Serializer\Annotation\SerializedName('requestId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $requestId = null;
    
    /**
     * Type of the validation error.
     * 
     * @var ?string $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;
    
	public function __construct()
	{
		$this->code = null;
		$this->message = null;
		$this->pathIssues = null;
		$this->requestId = null;
		$this->type = null;
	}
}
