<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PostAccountAccountIdOrdersOrderIdPayResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Operations\PostAccountAccountIdOrdersOrderIdPay200ApplicationJSON $postAccountAccountIdOrdersOrderIdPay200ApplicationJSONObject
     */
	
    public ?PostAccountAccountIdOrdersOrderIdPay200ApplicationJSON $postAccountAccountIdOrdersOrderIdPay200ApplicationJSONObject = null;
    
    /**
     * **Bad Request**\
     * 
     * When there are errors in the payload
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrdersOrderIdPay400ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrdersOrderIdPay400ApplicationJSONObject = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrdersOrderIdPay403ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrdersOrderIdPay403ApplicationJSONObject = null;
    
    /**
     * **Not found**\
     * 
     * When there are no accounts/orders/payment found
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrdersOrderIdPay404ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrdersOrderIdPay404ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrdersOrderIdPay500ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrdersOrderIdPay500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postAccountAccountIdOrdersOrderIdPay503ApplicationJSONObject
     */
	
    public ?array $postAccountAccountIdOrdersOrderIdPay503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postAccountAccountIdOrdersOrderIdPay200ApplicationJSONObject = null;
		$this->postAccountAccountIdOrdersOrderIdPay400ApplicationJSONObject = null;
		$this->postAccountAccountIdOrdersOrderIdPay403ApplicationJSONObject = null;
		$this->postAccountAccountIdOrdersOrderIdPay404ApplicationJSONObject = null;
		$this->postAccountAccountIdOrdersOrderIdPay500ApplicationJSONObject = null;
		$this->postAccountAccountIdOrdersOrderIdPay503ApplicationJSONObject = null;
	}
}
