<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


/** Message explaining the error. */
enum PostAccountAccountIdOrdersOrderIdPay404ApplicationJSONMessage: string
{
    case PaymentMethodNotFound = 'payment method not found.';
}
