<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class PostVerifyMicrodepositsRequest
{
    /**
     * Payment token Id
     * 
     * @var string $paymentToken
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=payment-token')]
    public string $paymentToken;
    
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\TheLogicStudio\ExactPayments\Models\Shared\MicroDepositVerificationRequest $microDepositVerificationRequest = null;
    
	public function __construct()
	{
		$this->paymentToken = "";
		$this->microDepositVerificationRequest = null;
	}
}
