<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PostOrdersOrderIdAccessToken404ApplicationJSONMetadata
{
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Operations\PostOrdersOrderIdAccessToken404ApplicationJSONMetadataMessage')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostOrdersOrderIdAccessToken404ApplicationJSONMetadataMessage $message = null;
    
	public function __construct()
	{
		$this->message = null;
	}
}
