<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PostPaymentResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * Payment Created
     * 
     * @var mixed $payment
     */
	
    public mixed $payment = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * **Bad Request**\
     * 
     * When there are errors in the payload
     * 
     * 
     * @var ?array<string, mixed> $postPayment400ApplicationJSONObject
     */
	
    public ?array $postPayment400ApplicationJSONObject = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $postPayment403ApplicationJSONObject
     */
	
    public ?array $postPayment403ApplicationJSONObject = null;
    
    /**
     * **Unprocessable Content**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postPayment422ApplicationJSONObject
     */
	
    public ?array $postPayment422ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postPayment500ApplicationJSONObject
     */
	
    public ?array $postPayment500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $postPayment503ApplicationJSONObject
     */
	
    public ?array $postPayment503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->payment = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postPayment400ApplicationJSONObject = null;
		$this->postPayment403ApplicationJSONObject = null;
		$this->postPayment422ApplicationJSONObject = null;
		$this->postPayment500ApplicationJSONObject = null;
		$this->postPayment503ApplicationJSONObject = null;
	}
}
