<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


class PutOrdersOrderIdResetResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Order Updated.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\OrderResponse $orderResponse
     */
	
    public ?\TheLogicStudio\ExactPayments\Models\Shared\OrderResponse $orderResponse = null;
    
    /**
     * **Access Denied**\
     * 
     * Credentials supplied do not grant access to the requested resource.
     * 
     * 
     * @var ?array<string, mixed> $putOrdersOrderIdReset403ApplicationJSONObject
     */
	
    public ?array $putOrdersOrderIdReset403ApplicationJSONObject = null;
    
    /**
     * **Not found**\
     * 
     * When there are no accounts/orders/payment found
     * 
     * 
     * @var ?array<string, mixed> $putOrdersOrderIdReset404ApplicationJSONObject
     */
	
    public ?array $putOrdersOrderIdReset404ApplicationJSONObject = null;
    
    /**
     * **Internal Server Error**
     * 
     * 
     * 
     * @var ?array<string, mixed> $putOrdersOrderIdReset500ApplicationJSONObject
     */
	
    public ?array $putOrdersOrderIdReset500ApplicationJSONObject = null;
    
    /**
     * **Service Unavailable**
     * 
     * 
     * 
     * @var ?array<string, mixed> $putOrdersOrderIdReset503ApplicationJSONObject
     */
	
    public ?array $putOrdersOrderIdReset503ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->orderResponse = null;
		$this->putOrdersOrderIdReset403ApplicationJSONObject = null;
		$this->putOrdersOrderIdReset404ApplicationJSONObject = null;
		$this->putOrdersOrderIdReset500ApplicationJSONObject = null;
		$this->putOrdersOrderIdReset503ApplicationJSONObject = null;
	}
}
