<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class PutOrganizationOrganizationIdOnboardingOnboardingIdRetryRuleRequest
{
    /**
     * ruleName is an existing rule name in the workflow assigned to a merchant application
     * 
     * @var \TheLogicStudio\ExactPayments\Models\Shared\OnboardingRetryRuleRequest $onboardingRetryRuleRequest
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \TheLogicStudio\ExactPayments\Models\Shared\OnboardingRetryRuleRequest $onboardingRetryRuleRequest;
    
    /**
     * The Onboarding Application identifier.
     * 
     * @var string $onboardingId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=onboardingId')]
    public string $onboardingId;
    
    /**
     * The Organization identifier.
     * 
     * @var string $organizationId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public string $organizationId;
    
	public function __construct()
	{
		$this->onboardingRetryRuleRequest = new \TheLogicStudio\ExactPayments\Models\Shared\OnboardingRetryRuleRequest();
		$this->onboardingId = "";
		$this->organizationId = "";
	}
}
