<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class PutOrdersOrderIdResetRequest
{
    /**
     * The Order identifier.
     * 
     * @var string $orderId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=orderId')]
    public string $orderId;
    
	public function __construct()
	{
		$this->orderId = "";
	}
}
