<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class PutOrganizationOrganizationIdOnboardingOnboardingIdStatusRequest
{
    /**
     * The Organization identifier.
     * 
     * @var string $organizationId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=organizationId')]
    public string $organizationId;
    
    /**
     * The Onboarding Application identifier.
     * 
     * @var string $onboardingId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=onboardingId')]
    public string $onboardingId;
    
    /**
     * The new status and the change reason
     * 
     * @var \TheLogicStudio\ExactPayments\Models\Shared\UpdateOnboardingStatusRequest $updateOnboardingStatusRequest
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \TheLogicStudio\ExactPayments\Models\Shared\UpdateOnboardingStatusRequest $updateOnboardingStatusRequest;
    
	public function __construct()
	{
		$this->organizationId = "";
		$this->onboardingId = "";
		$this->updateOnboardingStatusRequest = new \TheLogicStudio\ExactPayments\Models\Shared\UpdateOnboardingStatusRequest();
	}
}
