<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Operations;


enum VoidPaymentMessages: string
{
    case InvalidAuthorizationNumber = 'Invalid Authorization Number';
}
