<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class AccountReportDetailsMerchant
{
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantAddress')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AccountReportDetailsMerchantAddress $address = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('anticipatedTransAmounts')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantAnticipatedTransAmounts')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AccountReportDetailsMerchantAnticipatedTransAmounts $anticipatedTransAmounts = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('bankingDetails')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantBankingDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AccountReportDetailsMerchantBankingDetails $bankingDetails = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('businessProfile')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantBusinessProfile')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AccountReportDetailsMerchantBusinessProfile $businessProfile = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('businessRegistrationNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessRegistrationNumber = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('dbaName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dbaName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $email = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('entityType')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $entityType = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('establishedDate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $establishedDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('facebook')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $facebook = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('linkedIn')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $linkedIn = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('mcc')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mcc = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('numberOfEmployees')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $numberOfEmployees = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('onlinePresence')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $onlinePresence = null;
    
    /**
     * $principal
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantPrincipal> $principal
     */
	#[\JMS\Serializer\Annotation\SerializedName('principal')]
    #[\JMS\Serializer\Annotation\Type('array<TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantPrincipal>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $principal = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('telephone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $telephone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('twitter')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $twitter = null;
    
	public function __construct()
	{
		$this->address = null;
		$this->anticipatedTransAmounts = null;
		$this->bankingDetails = null;
		$this->businessProfile = null;
		$this->businessRegistrationNumber = null;
		$this->dbaName = null;
		$this->email = null;
		$this->entityType = null;
		$this->establishedDate = null;
		$this->facebook = null;
		$this->linkedIn = null;
		$this->mcc = null;
		$this->name = null;
		$this->numberOfEmployees = null;
		$this->onlinePresence = null;
		$this->principal = null;
		$this->telephone = null;
		$this->twitter = null;
	}
}
