<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class AccountReportDetailsMerchantBusinessProfile
{
	#[\JMS\Serializer\Annotation\SerializedName('acceptanceMethods')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\AccountReportDetailsMerchantBusinessProfileAcceptanceMethods')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AccountReportDetailsMerchantBusinessProfileAcceptanceMethods $acceptanceMethods = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('currentGateway')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $currentGateway = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('currentProcessor')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $currentProcessor = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('currentlyAcceptingPayments')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $currentlyAcceptingPayments = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('deliveryTimeframe')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $deliveryTimeframe = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('paymentTime')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $paymentTime = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('recurringServices')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $recurringServices = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('recurringServicesDescription')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $recurringServicesDescription = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('refundPolicyDescription')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $refundPolicyDescription = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('servicesDescription')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $servicesDescription = null;
    
	public function __construct()
	{
		$this->acceptanceMethods = null;
		$this->currentGateway = null;
		$this->currentProcessor = null;
		$this->currentlyAcceptingPayments = null;
		$this->deliveryTimeframe = null;
		$this->paymentTime = null;
		$this->recurringServices = null;
		$this->recurringServicesDescription = null;
		$this->refundPolicyDescription = null;
		$this->servicesDescription = null;
	}
}
