<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class AccountReportDetailsMerchantBusinessProfileAcceptanceMethods
{
	#[\JMS\Serializer\Annotation\SerializedName('_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('internet')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $internet = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('keyed')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $keyed = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('moto')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $moto = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('swipe')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $swipe = null;
    
	public function __construct()
	{
		$this->id = null;
		$this->internet = null;
		$this->keyed = null;
		$this->moto = null;
		$this->swipe = null;
	}
}
