<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * ApplicationTokenOutput - **Created**
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class ApplicationTokenOutput
{
    /**
     * List of Organization and Account identifiers that the created Application Token has access to.
     * 
     * @var ?array<string> $allowedAccounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('allowedAccounts')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $allowedAccounts = null;
    
    /**
     * Operations that can be performed with the created Application Token.
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\Permissions> $allowedPermissions
     */
	#[\JMS\Serializer\Annotation\SerializedName('allowedPermissions')]
    #[\JMS\Serializer\Annotation\Type('array<enum<TheLogicStudio\ExactPayments\Models\Shared\Permissions>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $allowedPermissions = null;
    
    /**
     * Application Token identifier in Exact Payments system.
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * Free text to quickly identify the created Application Token.
     * 
     * @var ?string $label
     */
	#[\JMS\Serializer\Annotation\SerializedName('label')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $label = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('mode')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\ApplicationTokenMode>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ApplicationTokenMode $mode = null;
    
    /**
     * Application Token used by non-human user to access other API endpoints. Place this token in the `Authorization` header when you call other endpoints. It will not expire.
     * 
     * @var ?string $token
     */
	#[\JMS\Serializer\Annotation\SerializedName('token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $token = null;
    
    /**
     * Determines the type of the token. This endpoint only creates Application Tokens. For more details, check our [guide](https://developer.exactpay.com/docs/Authentication).
     * 
     * @var ?string $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;
    
	public function __construct()
	{
		$this->allowedAccounts = null;
		$this->allowedPermissions = null;
		$this->id = null;
		$this->label = null;
		$this->mode = null;
		$this->token = null;
		$this->type = null;
	}
}
