<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class ApplicationTokenResponse
{
    /**
     * Operations that can be performed with the Application Tokens.
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\Permissions> $allowedPermissions
     */
	#[\JMS\Serializer\Annotation\SerializedName('allowedPermissions')]
    #[\JMS\Serializer\Annotation\Type('array<enum<TheLogicStudio\ExactPayments\Models\Shared\Permissions>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $allowedPermissions = null;
    
    /**
     * The date and time when the Application Token was created.
     * 
     * @var ?\DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * Application Token identifier in Exact Payments system.
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * Free text to quickly identify the created Application Token.
     * 
     * @var ?string $label
     */
	#[\JMS\Serializer\Annotation\SerializedName('label')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $label = null;
    
    /**
     * Determines the type of the token. This endpoint only retrieves Application Tokens. For more details, check our [guide](https://developer.exactpay.com/docs/Authentication).
     * 
     * @var ?string $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;
    
	public function __construct()
	{
		$this->allowedPermissions = null;
		$this->createdAt = null;
		$this->id = null;
		$this->label = null;
		$this->type = null;
	}
}
