<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Expected field type. It is only retrieved when `code = invalid_type`. */
enum AppleError400Expected: string
{
    case Array = 'array';
}
