<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Validation error code. The retrieved value will drive which extra fields will be shown. */
enum AppleError400Code: string
{
    case InvalidType = 'invalid_type';
    case TooSmall = 'too_small';
    case TooBig = 'too_big';
}
