<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * BankingDetails - Banking details of the Applicant's business for ACH Payments.
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class BankingDetails
{
    /**
     * Name of the Bank where the business holds the Demand Deposit Account(DDA) or the Current Account to which they wanted to receive the funds via ACH.
     * 
     * @var string $bankName
     */
	#[\JMS\Serializer\Annotation\SerializedName('bankName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $bankName;
    
    /**
     * A bank transit number is a unique 5-digit number used to identify the bank branch in Canada. This is only applicable for businesses based in Canada. The value must be a non-negative number string.
     * 
     * @var ?string $bankNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('bankNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $bankNumber = null;
    
    /**
     * Demand Deposit Account (or) Checking Account number. The value must be a non-negative number string.
     * 
     * @var string $ddaNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('ddaNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ddaNumber;
    
    /**
     * Plaid Access Token for the bank account verified through Plaid integration. When the Plaid access token is provided, the bank account will be added as a Verified Funding Source. Otherwise, the bank account will be added as Unverified Funding Source.
     * 
     * @var ?string $plaidAccessToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('plaidAccessToken')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $plaidAccessToken = null;
    
    /**
     * 9-digit Routing Number for the Organization or Account based in USA (or) 3-digit Institution number for the Organization or Account based in Canada. The value must be a non-negative number string.
     * 
     * @var string $routingNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('routingNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $routingNumber;
    
	public function __construct()
	{
		$this->bankName = "";
		$this->bankNumber = null;
		$this->ddaNumber = "";
		$this->plaidAccessToken = null;
		$this->routingNumber = "";
	}
}
