<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * BusinessRule - This verification service allows an underwriter to set custom decision rules based on individual Onboarding Application fields collected throughout the Onboarding process.
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class BusinessRule
{
    /**
     * The name assigned to the rule check.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Indicates what action the decision engine will take if the rule does not match its criteria.\
     * 
     * The possible values are *accept*, *reject*, *review*, or the name of another rule which should be executed for further evaluation in this ruleset.
     * 
     * @var string $onFail
     */
	#[\JMS\Serializer\Annotation\SerializedName('onFail')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $onFail;
    
    /**
     * Indicates the decision engine's action if the rule matches its criteria.\
     * 
     * The possible values are *accept*, *reject*, *review*, or the name of another rule which should be executed for further evaluation in this ruleset.
     * 
     * @var string $onPass
     */
	#[\JMS\Serializer\Annotation\SerializedName('onPass')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $onPass;
    
    /**
     * Criteria options that will be evaluated in the rule, the evaluation of these options will be against the body of the merchant.\
     * 
     * Should contain at least one of the properties.
     * 
     * 
     * @var array<\TheLogicStudio\ExactPayments\Models\Shared\BusinessRuleOptions> $options
     */
	#[\JMS\Serializer\Annotation\SerializedName('options')]
    #[\JMS\Serializer\Annotation\Type('array<TheLogicStudio\ExactPayments\Models\Shared\BusinessRuleOptions>')]
    public array $options;
    
    /**
     * Type of rule that will be evaluated by the decision engine
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\BusinessRuleType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\BusinessRuleType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BusinessRuleType $type = null;
    
	public function __construct()
	{
		$this->name = "";
		$this->onFail = "";
		$this->onPass = "";
		$this->options = [];
		$this->type = null;
	}
}
