<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


enum CardSchemaCardCvcIndicator: string
{
    case Present = 'present';
    case NotPresent = 'not-present';
    case Illegible = 'illegible';
}
