<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Indicates whether this card token is a `platform token` or a `network token`. */
enum CardDetailsSchemaTokenType: string
{
    case Platform = 'platform';
    case Network = 'network';
}
