<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class CardDetailsSchemaChecks
{
    /**
     * The response code from any AVS check.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\CardDetailsSchemaChecksAddressCheck $addressCheck
     */
	#[\JMS\Serializer\Annotation\SerializedName('addressCheck')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\CardDetailsSchemaChecksAddressCheck>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CardDetailsSchemaChecksAddressCheck $addressCheck = null;
    
    /**
     * The response code from any check on the CVD code.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\CardDetailsSchemaChecksCvcCheck $cvcCheck
     */
	#[\JMS\Serializer\Annotation\SerializedName('cvcCheck')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\CardDetailsSchemaChecksCvcCheck>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CardDetailsSchemaChecksCvcCheck $cvcCheck = null;
    
	public function __construct()
	{
		$this->addressCheck = null;
		$this->cvcCheck = null;
	}
}
