<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Delivery time frame that the business has for its products. */
enum DeliveryTimeframe: string
{
    case Immediate = 'Immediate';
    case Within7Days = 'Within 7 days';
    case Within14Days = 'Within 14 days';
    case Within30PlusDays = 'Within 30+ days';
}
