<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The Type of the Document being uploaded. */
enum DocumentUploadType: string
{
    case ArticlesOfIncorporation = 'articles-of-incorporation';
    case BankLetter = 'bank-letter';
    case BusinessLicense = 'business-license';
    case Passport = 'passport';
    case UtilityBill = 'utility-bill';
    case Ss4Form = 'ss-4-form';
    case DriversLicense = 'drivers-license';
    case Other = 'other';
    case IdCard = 'id-card';
}
