<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The three-digit country code where the Principal's driving license was issued. Refer to the three-digit country code defined in ISO 3166-1 alpha-3. */
enum DriversLicenseCountry: string
{
    case Usa = 'USA';
    case Can = 'CAN';
}
