<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The customer type as provisioned by Dwolla for the Account when the merchant is Onboarded with Dwolla. */
enum DwollaType: string
{
    case Unverified = 'unverified';
    case Personal = 'personal';
    case Business = 'business';
    case ReceiveOnly = 'receive-only';
}
