<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * Dwolla - Information about Onboarding details with Dwolla for ACH Payment enablement. Only Accounts are onboarded with Dwolla. Organizations are not onboarded with Dwolla and the status will always be `na` for Organizations.
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class Dwolla
{
    /**
     * The certification status of the Beneficial Owner (Principal) with Dwolla. This field will be populated when the Beneficial Owner's certification status is set or updated in Dwolla's system.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\BeneficialOwnershipCertifyStatus $beneficialOwnershipCertifyStatus
     */
	#[\JMS\Serializer\Annotation\SerializedName('beneficialOwnershipCertifyStatus')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\BeneficialOwnershipCertifyStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BeneficialOwnershipCertifyStatus $beneficialOwnershipCertifyStatus = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('businessClassification')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\BusinessClassification')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BusinessClassification $businessClassification = null;
    
    /**
     * The date and time when the Account is created or verified with Dwolla.
     * 
     * @var ?string $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $createdAt = null;
    
    /**
     * The documentation needed for Dwolla to verify the identity of the Business or the Owner's information. This field will be populated when the Dwolla's Onboarding status is `verification_document_needed`.
     * 
     * @var ?string $documentNeeded
     */
	#[\JMS\Serializer\Annotation\SerializedName('documentNeeded')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $documentNeeded = null;
    
    /**
     * The Customer Identifier received from Dwolla for the onboarded Account. This field will be populated when the merchant is onboarded with Dwolla for ACH Payment processing.
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * Status of Onboarding with Dwolla when ACH Payment is enabled for the onboarded Account. When ACH Payment enablement is not needed for the Account or the onboarded entity is an Organization then the status will be updated as `na` (Not Applicable).
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\Status $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\Status>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Status $status = null;
    
    /**
     * The customer type as provisioned by Dwolla for the Account when the merchant is Onboarded with Dwolla.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\DwollaType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\DwollaType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DwollaType $type = null;
    
	public function __construct()
	{
		$this->beneficialOwnershipCertifyStatus = null;
		$this->businessClassification = null;
		$this->createdAt = null;
		$this->documentNeeded = null;
		$this->id = null;
		$this->status = null;
		$this->type = null;
	}
}
