<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Status of Onboarding with Elavon when a card payment is enabled for the onboarded Account. When card payment enablement is not needed for the Account or if the onboarded entity is an organization then the status will be updated as `na` (Not Applicable). */
enum ElavonStatus: string
{
    case Na = 'na';
    case Started = 'started';
    case Failed = 'failed';
    case Completed = 'completed';
}
