<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * EmptyRuleOptionsField - This rule has no options so it can be defined as an empty object.
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class EmptyRuleOptionsField
{
	public function __construct()
	{
	}
}
