<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class FilterOnboardings
{
    /**
     * List of Organization identifiers that you have access to and which can be used to filter Onboardings Applications.
     * 
     * @var ?array<string> $account
     */
	#[\JMS\Serializer\Annotation\SerializedName('account')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $account = null;
    
    /**
     * The list of Onboarding statuses an Organization can use to filter the Onboarding Applications.
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\AccountStatus> $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('array<enum<TheLogicStudio\ExactPayments\Models\Shared\AccountStatus>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $status = null;
    
	public function __construct()
	{
		$this->account = null;
		$this->status = null;
	}
}
