<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** Entity type of the Business. */
enum MerchantEntityType: string
{
    case Llc = 'LLC';
    case Corp = 'Corp';
    case SoleProp = 'Sole Prop';
    case NonProfit = 'Non-Profit';
    case PublicCorp = 'Public Corp';
}
