<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class Merchant
{
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\UpdatableAddress')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdatableAddress $address = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('anticipatedTransAmounts')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\UpdatableAnticipatedTransAmounts')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdatableAnticipatedTransAmounts $anticipatedTransAmounts = null;
    
    /**
     * Banking details of the Account for ACH Payments, this field will be available ony for the Onboarding Applications submitted with the Banking Details.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\UpdatableBankingDetails $bankingDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('bankingDetails')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\UpdatableBankingDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdatableBankingDetails $bankingDetails = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('businessProfile')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\UpdatableBusinessProfile')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UpdatableBusinessProfile $businessProfile = null;
    
    /**
     * Tax identifier of the Business.
     * 
     * @var ?string $businessRegistrationNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('businessRegistrationNumber')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessRegistrationNumber = null;
    
    /**
     * Doing Business As Name.
     * 
     * @var ?string $dbaName
     */
	#[\JMS\Serializer\Annotation\SerializedName('dbaName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dbaName = null;
    
    /**
     * Contact Email of the Business.
     * 
     * @var ?string $email
     */
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $email = null;
    
    /**
     * Entity type of the Business.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\MerchantEntityType $entityType
     */
	#[\JMS\Serializer\Annotation\SerializedName('entityType')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\MerchantEntityType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MerchantEntityType $entityType = null;
    
    /**
     * Business Established Date.
     * 
     * @var ?\DateTime $establishedDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('establishedDate')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $establishedDate = null;
    
    /**
     * Facebook link of the Business.
     * 
     * @var ?string $facebook
     */
	#[\JMS\Serializer\Annotation\SerializedName('facebook')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $facebook = null;
    
    /**
     * LinkedIn link of the Business.
     * 
     * @var ?string $linkedIn
     */
	#[\JMS\Serializer\Annotation\SerializedName('linkedIn')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $linkedIn = null;
    
    /**
     * The business classification drives the [Merchant Category Codes](/operations/listMerchantCategoryCodes) selection. Prohibited or high-risk MCC codes are identified by Exact and are marked accordingly. Prohibited accounts are immediately declined while onboarding.
     * 
     * @var ?string $mcc
     */
	#[\JMS\Serializer\Annotation\SerializedName('mcc')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mcc = null;
    
    /**
     * The Name of the Business.
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Number of Employees of the Business.
     * 
     * @var ?float $numberOfEmployees
     */
	#[\JMS\Serializer\Annotation\SerializedName('numberOfEmployees')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $numberOfEmployees = null;
    
    /**
     * Website URL of the Business.
     * 
     * @var ?string $onlinePresence
     */
	#[\JMS\Serializer\Annotation\SerializedName('onlinePresence')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $onlinePresence = null;
    
    /**
     * The details for the Principal owner(s) of the Business.
     * 
     * @var ?array<\TheLogicStudio\ExactPayments\Models\Shared\UpdatablePrincipal> $principal
     */
	#[\JMS\Serializer\Annotation\SerializedName('principal')]
    #[\JMS\Serializer\Annotation\Type('array<TheLogicStudio\ExactPayments\Models\Shared\UpdatablePrincipal>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $principal = null;
    
    /**
     * Telephone Number of the Business.
     * 
     * @var ?string $telephone
     */
	#[\JMS\Serializer\Annotation\SerializedName('telephone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $telephone = null;
    
    /**
     * Whether the Organization or Account has agreed to the Terms and Conditions. This field will be available in response only when the termsNConditions were sent to exact payments when the Onboarding Application was created.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\MerchantTermsNConditions $termsNConditions
     */
	#[\JMS\Serializer\Annotation\SerializedName('termsNConditions')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\MerchantTermsNConditions')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MerchantTermsNConditions $termsNConditions = null;
    
    /**
     * Twitter link of the Business.
     * 
     * @var ?string $twitter
     */
	#[\JMS\Serializer\Annotation\SerializedName('twitter')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $twitter = null;
    
	public function __construct()
	{
		$this->address = null;
		$this->anticipatedTransAmounts = null;
		$this->bankingDetails = null;
		$this->businessProfile = null;
		$this->businessRegistrationNumber = null;
		$this->dbaName = null;
		$this->email = null;
		$this->entityType = null;
		$this->establishedDate = null;
		$this->facebook = null;
		$this->linkedIn = null;
		$this->mcc = null;
		$this->name = null;
		$this->numberOfEmployees = null;
		$this->onlinePresence = null;
		$this->principal = null;
		$this->telephone = null;
		$this->termsNConditions = null;
		$this->twitter = null;
	}
}
