<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class NewPaymentPaymentMethod1ApplePay
{
    /**
     * Card holder name.
     * 
     * @var ?string $cardholder
     */
	#[\JMS\Serializer\Annotation\SerializedName('cardholder')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cardholder = null;
    
    /**
     * The cryptogram returned by Apple Pay. Note: if the response from Apple contains an `eciIndicator` value, you MUST pass this value to us using the `ecommerce_flag` attribute in the `options` request element.
     * 
     * @var string $cryptogram
     */
	#[\JMS\Serializer\Annotation\SerializedName('cryptogram')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cryptogram;
    
    /**
     * Expiration month for the card.
     * 
     * @var string $expiryMonth
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiryMonth')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $expiryMonth;
    
    /**
     * Expiration year for the card.
     * 
     * @var string $expiryYear
     */
	#[\JMS\Serializer\Annotation\SerializedName('expiryYear')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $expiryYear;
    
    /**
     * Card number.
     * 
     * @var string $number
     */
	#[\JMS\Serializer\Annotation\SerializedName('number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $number;
    
    /**
     * The transaction ID returned by Apple Pay.
     * 
     * @var string $transactionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('transactionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $transactionId;
    
	public function __construct()
	{
		$this->cardholder = null;
		$this->cryptogram = "";
		$this->expiryMonth = "";
		$this->expiryYear = "";
		$this->number = "";
		$this->transactionId = "";
	}
}
