<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;

use \TheLogicStudio\ExactPayments\Utils\SpeakeasyMetadata;
class OnboardingDocumentUploadRequest
{
    /**
     * The Document Request identifier if you are uploading the Document in response to a Document Request you created.
     * 
     * @var ?string $documentRequest
     */
	#[SpeakeasyMetadata('multipartForm:name=documentRequest')]
    public ?string $documentRequest = null;
    
    /**
     * The binary data of the Document being uploaded. The following file types are supported `bmp`,`csv`,`doc`,`docx`,`jpg`,`pdf`,`png`,`rtf`,`txt`,`xls` and `xlsx`. An HTTP `500 Internal Server Error` code with a JSON response will be returned when the Document is not uploaded.
     * 
     * @var \TheLogicStudio\ExactPayments\Models\Shared\Files $files
     */
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public Files $files;
    
    /**
     * The Name of the Document being uploaded.
     * 
     * @var string $name
     */
	#[SpeakeasyMetadata('multipartForm:name=name')]
    public string $name;
    
    /**
     * A boolean string. To upload a Document for soft deleted Onboarding, pass "true". This field is not required if you upload a Document for the active Onboarding.
     * 
     * @var ?string $onboardingIsDeleted
     */
	#[SpeakeasyMetadata('multipartForm:name=onboardingIsDeleted')]
    public ?string $onboardingIsDeleted = null;
    
    /**
     * The unique identifier of the Principal you are uploading the Document for. This field is required if you upload the Document to one of the Principals added in the Onboarding Application.
     * 
     * @var ?string $principal
     */
	#[SpeakeasyMetadata('multipartForm:name=principal')]
    public ?string $principal = null;
    
    /**
     * The Type of the Document being uploaded.
     * 
     * @var \TheLogicStudio\ExactPayments\Models\Shared\DocumentUploadType $type
     */
	#[SpeakeasyMetadata('multipartForm:name=type')]
    public DocumentUploadType $type;
    
	public function __construct()
	{
		$this->documentRequest = null;
		$this->files = new \TheLogicStudio\ExactPayments\Models\Shared\Files();
		$this->name = "";
		$this->onboardingIsDeleted = null;
		$this->principal = null;
		$this->type = \TheLogicStudio\ExactPayments\Models\Shared\DocumentUploadType::ArticlesOfIncorporation;
	}
}
