<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class OnboardingTermsNConditions
{
    /**
     * Whether the Onboarding Applicant agrees to [Dwolla's terms and conditions](https://www.dwolla.com/legal/platform-agreement/).
     * 
     * @var ?bool $dwolla
     */
	#[\JMS\Serializer\Annotation\SerializedName('dwolla')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $dwolla = null;
    
    /**
     * Whether the Onboarding Applicant agrees to Exact Payment's terms and conditions. 
     * 
     * @var ?bool $exactPayments
     */
	#[\JMS\Serializer\Annotation\SerializedName('exactPayments')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $exactPayments = null;
    
    /**
     * Whether the Onboarding Applicant agrees to Exact Payment's notification and communication policies.
     * 
     * @var ?bool $notifications
     */
	#[\JMS\Serializer\Annotation\SerializedName('notifications')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $notifications = null;
    
	public function __construct()
	{
		$this->dwolla = null;
		$this->exactPayments = null;
		$this->notifications = null;
	}
}
