<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * OnboardingRetryRuleRequest - ruleName is an existing rule name in the workflow assigned to a merchant application
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class OnboardingRetryRuleRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('ruleName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ruleName;
    
	public function __construct()
	{
		$this->ruleName = "";
	}
}
