<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The time at which the customer makes the payment to the business. */
enum PaymentTime: string
{
    case UponPurchase = 'Upon Purchase';
    case UponDownload = 'Upon Download';
    case AtTimeOfDelivery = 'At Time of Delivery';
    case Other = 'Other';
}
