<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The Status of the Rule executed or being executed. */
enum RuleStatus: string
{
    case Passed = 'Passed';
    case Failed = 'Failed';
    case Errored = 'Errored';
    case PendingChecks = 'PendingChecks';
}
