<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class SettlementReportDetailsReference
{
	#[\JMS\Serializer\Annotation\SerializedName('customerRef')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerRef = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('referenceNo')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $referenceNo = null;
    
	public function __construct()
	{
		$this->customerRef = null;
		$this->referenceNo = null;
	}
}
