<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


class SettlementReportDetailsVoidDetails
{
    /**
     * $list
     * 
     * @var ?array<string> $list
     */
	#[\JMS\Serializer\Annotation\SerializedName('list')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $list = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('remaining')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $remaining = null;
    
	public function __construct()
	{
		$this->list = null;
		$this->remaining = null;
	}
}
