<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The position or title held by the Principal owner or the Authorized Person of the Organization. */
enum TitleValues: string
{
    case CEOPresident = 'CEO/President';
    case OwnerFounder = 'Owner/Founder';
    case VPDirector = 'VP/Director';
    case Manager = 'Manager';
    case Administrator = 'Administrator';
    case Other = 'Other';
}
