<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/** The field that will be used to evaluate the rule */
enum UnderwritingRuleOptionsField: string
{
    case MerchantAddressCountry = 'merchant.address.country';
    case MerchantAddressCountrySubdivision = 'merchant.address.countrySubdivision';
    case MerchantEstablishedDate = 'merchant.establishedDate';
    case MerchantName = 'merchant.name';
    case MerchantDbaName = 'merchant.dbaName';
    case MerchantTelephone = 'merchant.telephone';
    case MerchantEmail = 'merchant.email';
    case MerchantOnlinePresence = 'merchant.onlinePresence';
    case MerchantAddressLine1 = 'merchant.address.line1';
    case MerchantAddressCity = 'merchant.address.city';
    case MerchantAddressPostalCode = 'merchant.address.postalCode';
    case MerchantFacebook = 'merchant.facebook';
    case MerchantBusinessRegistrationNumber = 'merchant.businessRegistrationNumber';
    case MerchantTwitter = 'merchant.twitter';
    case MerchantLinkedin = 'merchant.linkedin';
    case MerchantBankingDetailsBankName = 'merchant.bankingDetails.bankName';
    case MerchantBankingDetailsRoutingNumber = 'merchant.bankingDetails.routingNumber';
    case MerchantEntityType = 'merchant.entityType';
    case MerchantPrincipalAddressCountry = 'merchant.principal.address.country';
    case MerchantPrincipalAddressCountrySubdivision = 'merchant.principal.address.countrySubdivision';
    case MerchantPrincipalFirstName = 'merchant.principal.firstName';
    case MerchantPrincipalLastName = 'merchant.principal.lastName';
    case MerchantPrincipalTelephone = 'merchant.principal.telephone';
    case MerchantPrincipalEmail = 'merchant.principal.email';
    case MerchantPrincipalAddressLine1 = 'merchant.principal.address.line1';
    case MerchantPrincipalAddressCity = 'merchant.principal.address.city';
    case MerchantPrincipalAddressPostalCode = 'merchant.principal.address.postalCode';
    case MerchantPrincipalPercentOfOwnership = 'merchant.principal.percentOfOwnership';
    case MerchantMcc = 'merchant.mcc';
    case MerchantBusinessProfileDeliveryTimeframe = 'merchant.businessProfile.deliveryTimeframe';
    case MerchantAnticipatedTransAmountsAverageTicketSize = 'merchant.anticipatedTransAmounts.averageTicketSize';
    case MerchantAnticipatedTransAmountsAnticipatedMonthlyVolume = 'merchant.anticipatedTransAmounts.anticipatedMonthlyVolume';
    case MerchantAnticipatedTransAmountsMaxTicketSize = 'merchant.anticipatedTransAmounts.maxTicketSize';
    case MerchantBusinessProfileServicesDescription = 'merchant.businessProfile.servicesDescription';
    case MerchantBusinessProfileAcceptanceMethodsMoto = 'merchant.businessProfile.acceptanceMethods.moto';
    case MerchantBusinessProfileAcceptanceMethodsInternet = 'merchant.businessProfile.acceptanceMethods.internet';
    case MerchantBusinessProfileAcceptanceMethodsSwipe = 'merchant.businessProfile.acceptanceMethods.swipe';
    case MerchantBusinessProfileAcceptanceMethodsKeyed = 'merchant.businessProfile.acceptanceMethods.keyed';
}
