<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


/**
 * UnderwritingRule5 - This authentication verification allows Exat Payments to authenticate a user's depository account information through the Plaid OAuth authorization service, making it easy to initiate credits or debits to the correct business account.
 * 
 * @package TheLogicStudio\ExactPayments\Models\Shared
 * @access public
 */
class UnderwritingRule5
{
    /**
     * The name assigned to the rule check.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Indicates what action the decision engine will take if the rule does not match its criteria.\
     * 
     * The possible values are *accept*, *reject*, *review*, or the name of another rule which should be executed for further evaluation in this ruleset.
     * 
     * @var string $onFail
     */
	#[\JMS\Serializer\Annotation\SerializedName('onFail')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $onFail;
    
    /**
     * Indicates the decision engine's action if the rule matches its criteria.\
     * 
     * The possible values are *accept*, *reject*, *review*, or the name of another rule which should be executed for further evaluation in this ruleset.
     * 
     * @var string $onPass
     */
	#[\JMS\Serializer\Annotation\SerializedName('onPass')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $onPass;
    
    /**
     * This rule has no options so it can be defined as an empty object.
     * 
     * @var ?\TheLogicStudio\ExactPayments\Models\Shared\EmptyRuleOptionsField $options
     */
	#[\JMS\Serializer\Annotation\SerializedName('options')]
    #[\JMS\Serializer\Annotation\Type('TheLogicStudio\ExactPayments\Models\Shared\EmptyRuleOptionsField')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?EmptyRuleOptionsField $options = null;
    
    /**
     * Type of rule that will be evaluated by the decision engine
     * 
     * @var \TheLogicStudio\ExactPayments\Models\Shared\UnderwritingRuleType5 $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<TheLogicStudio\ExactPayments\Models\Shared\UnderwritingRuleType5>')]
    public UnderwritingRuleType5 $type;
    
	public function __construct()
	{
		$this->name = "";
		$this->onFail = "";
		$this->onPass = "";
		$this->options = null;
		$this->type = \TheLogicStudio\ExactPayments\Models\Shared\UnderwritingRuleType5::PlaidAuth;
	}
}
