<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace TheLogicStudio\ExactPayments\Models\Shared;


enum UpdateOnboardingStatusRequestStatus: string
{
    case InProgress = 'inProgress';
    case Withdrawn = 'withdrawn';
    case Pended = 'pended';
    case Approved = 'approved';
    case Declined = 'declined';
    case AccountClosed = 'accountClosed';
    case ReviewNeeded = 'reviewNeeded';
    case InRiskReview = 'inRiskReview';
    case Terminated = 'terminated';
}
